services:
  home-db-mysql:
    image: mysql:8.4.3
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
      - mysql_hms_user_password
      - mysql_hb_user_password
    networks:
      - home_network
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD"
      timeout: 5s
      interval: 5s
      retries: 10

volumes:
  db_data:
    name: home_db_mysql_data
secrets:
  mysql_root_password:
    file: C:\\dev\\secrets\\mysql_root_password.txt
  mysql_hms_user_password:
    file: C:\\dev\\secrets\\mysql_hms_user_password.txt
  mysql_hb_user_password:
    file: C:\\dev\\secrets\\mysql_hb_user_password.txt

networks:
  home_network:
    external: true
