version: "3.8"
services:
  oracle-xe:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle-xe
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=your_password
      - ORACLE_CHARACTERSET=AL32UTF8
      - TZ=Asia/Tokyo
    volumes:
      - oracle-xe-data:/opt/oracle/oradata

volumes:
  oracle-xe-data: